[workspace]
authors = ["bobo-baggins <urbanecoguard@gmail.com>"]
channels = ["conda-forge"]
name = "pyqualw2"
platforms = ["linux-64"]
version = "0.1.0"


# [dependencies]
# typer = ">=0.20.0,<0.21"
# pandas = ">=2.3.3,<3"
# python-lsp-server = ">=1.13.2,<2"
# ruff = ">=0.14.5,<0.15"
# pathlib = ">=1.0.1,<2"
# typing_extensions = ">=4.15.0,<5"
# rich = ">=14.2.0,<15"

[tool.pixi.workspace]
name = "pyqualw2"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pyqualw2 = { path = ".", editable = true }

[tool.pixi.tasks]
